import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Box from "@mui/system/Box";
import { Header1 } from "@/components/Header1";
import { Middle } from "@/components/Middle";
import { Footer } from "@/components/Footer";
import { MainMid } from "@/components/MainMid";
import All from "@/components/main";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <Box>
          <All></All>
        </Box>
        <Box>
         <MainMid></MainMid>
        </Box>
      </main>
    </>
  );
}
