import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Box from "@mui/system/Box";
import priceContent from "@/components/TextContent";
import Items from "@/components/Items";
import Pricing_page from "@/components/Pricing_page";
import Contact from "@/components/Contact_page";
import { Container } from "@mui/material";


const inter = Inter({ subsets: ["latin"] });



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Pricing_page></Pricing_page>          
        </Box>
        <Box sx={{pt:"100px",}}>
          <Contact></Contact>_
        </Box>    
      </main>
    </>
  );
}
